name: oblns
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^20.3.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_database: ^12.1.2
  cloud_functions: ^6.0.6
  firebase_messaging: ^16.1.1
  firebase_analytics: ^12.1.1
  firebase_ui_auth: ^3.0.1
  google_sign_in: ^7.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^3.1.0
  hooks_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.0.0

  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^12.0.1
  dart_geohash: ^2.1.0
  geoflutterfire_plus: ^0.0.5

  google_fonts: ^8.0.0
  vector_math: ^2.1.4
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  lottie: ^3.3.0
  flutter_spinkit: ^5.2.1
  flutter_blurhash: ^0.9.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.2

  shared_preferences: ^2.3.5
  flutter_secure_storage: ^10.0.0
  vibration: ^3.1.5
  logger: ^2.5.0
  intl: ^0.20.2
  uuid: ^4.5.1
  encrypt: ^5.0.3
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  http: ^1.3.0
  crypto: ^3.0.6
  image_picker: ^1.1.2

  currency_picker: ^2.0.0
  json_annotation: ^4.9.0
  firebase_data_connect: ^0.2.2+2

  connectivity_plus: ^6.0.3

  web3dart: ^2.6.1

  mqtt_client: ^9.8.1

  ml_algo: ^16.17.1
  ml_dataframe: ^1.2.0
  ml_linalg: ^13.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.4.15
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.9.3
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4
  path: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"
